all:
	cd mod && make
	cd user && make

clean:
	cd mod && make clean
	cd user && make clean

## module add raspberry
## KERNEL=kernel7
## LINUX_SOURCE=/tmp/compile/jiaoziyang/linux_source/linux
## make -C $LINUX_SOURCE ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- SUBDIRS=$PWD modules